### ISSUE TITLE
src/minix/commands/mail/mail.c:765]: (error) Resource leak: fp

### ISSUE THREAD

**Issue by dcb314** [Stichting-MINIX-Research-Foundation/minix#109]
Source code is

void dohelp()
{
  FILE *fp;
  char buffer[80];

  if ( (fp = fopen(HELPFILE, "r")) == NULL)
    fprintf(stdout, "can't open helpfile %s\n", HELPFILE);
  else
    while (fgets(buffer, 80, fp))
        fputs(buffer, stdout);
}

Suggest add call to fclose

**Comment by tcort** [comment]
I don't think `fp` is leaked. In this case, `fopen()` always fails (i.e. returns `NULL`) because there is no help file at `/usr/lib/mail.help`. To demonstrate this: send a mail to yourself, run the `mail` command with no arguments, type an `*` and press enter to invoke `dohelp()` -- you'll get the "can't open helpfile" message.

There are probably lots of improvements that could be made to Minix's `mail` command (this leak, the helpfile, and much more), but it might be more beneficial to import the [mail](http://git.minix3.org/index.cgi?p=netbsd.git;a=tree;f=usr.bin/mail;hb=HEAD) command from NetBSD instead of trying to improve the old Minix `mail` program. The NetBSD version is probably more featureful and well tested. There is a [guide](http://wiki.minix3.org/doku.php?id=developersguide:portingnetbsduserland) if you're interested in going down that path.

**Comment by dcb314** [comment]
>I don't think fp is leaked.

I'd be grateful if you could show me please where the call to fclose
(that matches the call to fopen) is.

In normal operation, this code seems to leak.

**Comment by tcort** [comment]
> In normal operation, this code seems to leak.

I've tested this program, and the call to `fopen()` always fails for me (due to the help file not being present). When `fopen()` fails, `fp` isn't allocated, so nothing is leaked.

To fix this properly, one would need to add the `fclose()` call and a help file. There are other chances for leaked descriptors too (I think `readbox()` might leak one), so those would need to be identified and fixed. The code is K&R style, so that would need to be updated, etc, etc.

All in all, there is a lot of work to do to get `./minix/commands/mail/mail.c` in shape. What I'm saying is that it might be more beneficial to import/port the `mail` command from NetBSD and get rid of the Minix `mail` command.

**Comment by dcvmoole** [comment]
Importing NetBSD's mail is definitely the way forward. In the meantime I for one don't mind fixing this particular bug though, even if there are few real-world consequences of doing so. Let's see if this can make it into 3.4.

**Comment by tcort** [comment]
Just to follow up on some other things I mentioned. I looked in `readbox()`. It doesn't appear to leak `boxfp`. `boxfp` is a global variable which is later closed (or `freopen()`'d), so that seems fine.

As for importing NetBSD `mail`, it compiles but the docs depend on `groff`. The NetBSD `mail` program itself depends on the `sendmail` command which is provided by `postfix`. I haven't looked into how hard it would be to get `postfix` and `groff` imported.

**Comment by sambuc** [comment]
* groff being GNU, this requires a fetch script currently. I would personally wait until we know what to do, even it this means disabling building the doc for a while. This is actually already the case in a couple of other places.

 * I could not find a BSD replacement to groff so far. It's a shame as we have almost no GNU programs left in the base system (binutils, GCC & their dependencies, that is all), and this could mean importing a new one, just for some documentation. Maybe we could pre-generate it as a workaround?

 * postfix is in `./external/ibm-public/postfix`, so no such issues, the only question is does it work on MINIX, or do we need to implement some feature / patch postfix?

**Comment by tcort** [comment]
This has been fixed in b88949904f55e7591b64919f3c92207f41f5b478

**Comment by tcort** [comment]
I'm going to close this one since the initially reported issue  (missing fclose ()) has been fixed. Please reopen if there's anything I missed.

Thanks for the report!
