### ISSUE TITLE
src/minix/lib/liblwip/core/dhcp.c:1381]: (style) Array index 'offset' is used before limits check.

### ISSUE THREAD

**Issue by dcb314** [Stichting-MINIX-Research-Foundation/minix#110]
Source code is

  while((q != NULL) && (options[offset] != DHCP_OPTION_END) && (offset < offset_max)) {

Suggest sanity check offset before use.

**Comment by dcvmoole** [comment]
Despite being in the minix/ subdirectory, the LWIP library is imported code (I know, I know..). I am closing this issue because we will not be fixing it for that reason. However, reporting the bug to the LWIP project would be highly appreciated, as it seems to be present even in the current LWIP version:

http://git.savannah.gnu.org/cgit/lwip.git/tree/src/core/ipv4/dhcp.c#n1423

We intend on importing a new version of this LWIP library in the near future, so we will be getting any bugfixes applied to it as well. Thank you!

**Comment by dcb314** [comment]
>However, reporting the bug to the LWIP project would be highly appreciated

Done.

**Comment by dcvmoole** [comment]
Thanks again :)
