### ISSUE TITLE
Deletion of unnecessary checks before specific function calls

### ISSUE THREAD

**Issue by elfring** [Stichting-MINIX-Research-Foundation/minix#115]
A couple of functions performs input parameter validation before their implementations will try further actions with side effects. Some calling functions perform similar safety checks.

Functions which release a system resource are occasionally documented in the way that they tolerate the passing of a null pointer for example.
I do not see a need because of this fact that a function caller repeats a corresponding check.

Now I would like to propose such a change again.
 1. Extension of the test infrastructure for [the analysis tool "Coccinelle"](http://coccinelle.lip6.fr/ "Program transformation with Coccinelle?")

 Semantic patch patterns can help to identify update candidates also in the MINIX source file hierarchy.
 2. Clarification for some automated update suggestions

 [My source code search approach found some functions](https://groups.google.com/d/msg/minix3/7DE_msHfzQA/R38nIjuT-REJ "Patching with Coccinelle?: Deletion of unnecessary checks before specific function calls") which might need another review and corresponding corrections around MINIX 3. Further software development will point even more potentially open issues out.

**Comment by dcvmoole** [comment]
>  I do not see a need because of this fact that a function caller repeats a corresponding check.

It is not necessarily a bad thing. Checks that are duplicated between functions often actually increase code readability (since, in lieu of comments, it allows a function to be better understood in isolation - that is, without also looking at all its callers) and make the code more robust against refactoring. We are not overly concerned with the performance aspect just yet. My usual strategy is to use an actual if-check in the caller and then an assert in the callee, but I'd be almost inclined to call that a style choice.

In any case, if finding a bit of small-scale redundancy is the main advantage of "Coccinelle" then it hardly sounds worth the investment of adding it to our test infrastructure. The tool itself is GPL and requires a whole bunch of nonstandard environment tools, so integrating it into the base system is out of the question.

By the way, your link about having found some functions links to a post that states you found some functions. Some actual code examples might help in determining how serious this issue really is.

**Comment by elfring** [comment]
>Checks that are duplicated between functions often actually increase code readability …

How many understanding efforts result from the presence of extra (or redundant) source code?


>In any case, if finding a bit of small-scale redundancy is the main advantage of "Coccinelle" then it hardly sounds worth the investment of adding it to our test infrastructure.

Did you notice how many source files from other free software were improved by the use of semantic patch scripts already?


>The tool itself is GPL and requires a whole bunch of nonstandard environment tools, so integrating it into the base system is out of the question.

Would you like to look again for [extensions to your software development toolbox](http://pkgsrc.se/devel/coccinelle "Tool for writing and applying semantic patches")?


>Some actual code examples might help in determining how serious this issue really is.

How do you think about another look into [a similar problem report for NetBSD](http://gnats.netbsd.org/cgi-bin/query-pr-single.pl?number=49272 "Patching with Coccinelle?: Deletion of unnecessary checks before specific function calls")?

**Comment by dcvmoole** [comment]
> How many understanding efforts result from the presence of extra (or redundant) source code?
I just explained how it may actually help people to understand code. It's not black and white. Either way, with our limited manpower we (= people doing stuff) don't have the luxury to spend lots of time on taking care of really minor issues, and you're not making a good case that this is more than really minor issues. We are, however, happy to take patches for just about anything.
> Did you notice how many source files from other free software were improved by the use of semantic patch scripts already?
No, nor was this your original point. If the tool can do more than find a few really minor issues, then perhaps you should be presenting a better case for it.
> Would you like to look again for extensions to your software development toolbox?
Would you like to do research on what the MINIX3 project calls its "base system", and what its license is?
> How do you think about another look into a similar problem report for NetBSD?
Am I supposed to decode that email attachment myself? What prevents you from uploading the tool's output on MINIX3 somewhere so that we can actually look at it?

**Comment by elfring** [comment]
>We are, however, happy to take patches for just about anything.

How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2FC.2B.2B "Tools for static code analysis") also for your software?

>Would you like to do research on what the MINIX3 project calls its "base system", and what its license is?

I assume that [the software collection](http://wiki.minix3.org/doku.php?id=developersguide:overviewofminixuserland#categories_of_netbsd_userland "Categories of NetBSD userland") can be extended with updated packages.


>Am I supposed to decode that email attachment myself?

I am also curious when the web interface of the GNU project's issue-tracking software will offer a more convenient interface for the reuse of content from attachments.


>What prevents you from uploading the tool's output on MINIX3 somewhere so that we can actually look at it?

* How much do you distinguish NetBSD components from the core software?
* Which storage location would be appropriate for the results from an updated source code analysis?

**Comment by dcvmoole** [comment]
> Which storage location would be appropriate for the results from an updated source code analysis?
I believe you can attach files to this issue here. At least it says so right below where I'm typing this right now.

Beyond that, let's save the discussion about topics not related to the original issue for another time.

**Comment by elfring** [comment]
>I believe you can attach files to this issue here.

I find that the GitHub upload interface does not look promising on this evening.


A static code analysis (by one of my semantic script approaches) on the source files in the MINIX 3 repository (according to the commit 373b793920deea2122e25de227b3388b5ad4716d on 2016-01-28) shows by an advanced application of the software "Coccinelle 1.0.4" that there might be 328 function implementations which could be improved by the deletion of redundant checks.

**Comment by elfring** [comment]
>I believe you can attach files to this issue here.

[The GitHub upload interface](https://github.com/blog/2061-attach-files-to-comments "Attach files to comments") will need further fine-tuning.
(Do I eventually get a wrong impression from varying network responsiveness?)

**Comment by elfring** [comment]
Dear David,

Thanks for your general interest.


>     I believe you can attach files to this issue here.

I am curious if the desired attachment will be integrated by an other
communication channel then.
Would you like to give the update suggestion in this compressed archive (79.8 kB)
another look?

Regards,
Markus

**Comment by dcvmoole** [comment]
I took a quick look at the patch that you sent to me by email. The report is mostly about code that we import from various other places; we will not change that code ourselves, instead you should report it to the original projects (NetBSD, lwIP, etc). For the relatively small number of cases affecting our code, I looked into one report, namely about libsffs (which I wrote), and the report is plain wrong: the proposed removal of checks around put_inode would simply break the code. In summary, I don't think that in its current state this report is helpful at all, and I'm closing this issue for now. Thank you for your efforts though!

**Comment by elfring** [comment]
>I took a quick look …

Thanks.


>The report is mostly about code that we import from various other places; …

I guess that such a result can be usually expected when the Minix kernel is so "micro" that other program implementations from the bundled software collection provide more source code to inspect.


>… I looked into one report, namely about libsffs (which I wrote), and the report is plain wrong: the proposed removal of checks around put_inode would simply break the code.

Does the current approach point any places out also for further considerations there?
* Can a call of [the macro "`dprintf`"](https://github.com/Stichting-MINIX-Research-Foundation/minix/blob/41a30155b93b5fdc3b6a018df059658fbb97e8b4/minix/lib/libsffs/inc.h#L13 "Debug output") be moved behind assertions within [the implementation of the function "`put_inode`"](https://github.com/Stichting-MINIX-Research-Foundation/minix/blob/41a30155b93b5fdc3b6a018df059658fbb97e8b4/minix/lib/libsffs/inode.c#L124 "Update candidate: put_inode()")?
* Would you like to suggest any ideas to reduce the probability for false positives from static source code analysis any further?

**Comment by dcvmoole** [comment]
I hope you can understand that if this tool does something that is not particularly noteworthy and even gets that one thing wrong, I'm not particularly interested in spending further time on it..

**Comment by elfring** [comment]
I can understand to some degree that you do not like the shown source code analysis result at the moment. Can it be that you would like to push this issue away a bit too early?

How do you think about to improve the mentioned function implementation like the following?
```diff
diff --git a/minix/lib/libsffs/inode.c b/minix/lib/libsffs/inode.c
index 499e941..398422a 100644
--- a/minix/lib/libsffs/inode.c
+++ b/minix/lib/libsffs/inode.c
@@ -131,15 +131,16 @@ void put_inode(struct inode *ino)
  * reached zero, mark the inode as cached or free.
  */
 
-  dprintf(("%s: put_inode(%p) ['%s']\n", sffs_name, ino, ino->i_name));
+  if (__predict_false(!ino))
+       panic("Null pointer was passed by the parameter \"ino\".");
 
-  assert(ino != NULL);
-  assert(ino->i_ref > 0);
+  if (__predict_false(0 >= ino->i_ref))
+       panic("suspicious inode reference count");
 
-  ino->i_ref--;
+  dprintf(("%s: put_inode(%p) ['%s']\n", sffs_name, ino, ino->i_name));
 
   /* If there are still references to this inode, we're done here. */
-  if (ino->i_ref > 0)
+  if ((--ino->i_ref) > 0)
        return;
 
   /* Close any file handle associated with this inode. */
```

**Comment by sambuc** [comment]
I have a couple of issues:

**A.** The only potential problem I see here is the dprintf (which is transformed into actual code only when specific options are turned on) which is before the first assert. Otherwise this piece of code is perfectly fine as far as I can tell.

**B.** The proposed patch introduces for the first time new macros/functions which are designed for optimization:
 * Without doing the proper benchmarking, to prove it actually brings a noticeable gain.
 * To solve an issue not in the code, but in an external analysis tool.

**C.** As proposed, the patch also breaks the intent of asserts as this transform **optional** code into always-on code. This might be a surprise, but the minix source code can be compiled without asserts, and run as expected.

**D.** While a minor thing, I don't see the gain of replacing 
```C
ino->i_ref--;
if (ino->i_ref > 0)
```
with 
```C
if ((--ino->i_ref) > 0)
```
To me, this just makes the code less readable.

**Comment by dcvmoole** [comment]
> Can it be that you would like to push this issue away a bit too early?

What issue? What are you even trying to achieve here? The assert and dprintf debugging statements are indeed in the wrong order (a minor bug, since the assert should never trigger anyway), but what does that have to do with your analysis tool concluding that NULL pointers can be passed safely to put_inode() (which would introduce a major bug that functionally breaks libsffs)? Or are we no longer talking about the tool now?

**Comment by elfring** [comment]
>The assert and dprintf debugging statements are indeed in the wrong order …

Thanks that you can agree to this detail. Do you need another bug report to fix it?


>… but what does that have to do with your analysis tool concluding that NULL pointers can be passed safely to put_inode() …?

My static source code analysis approach is in development for a while in a similar way as other free tools from [this application domain](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2FC.2B.2B "Tools for static code analysis"). It pointed a few update candidates out which you identified as inappropriate for the moment. I took another look at the mentioned function implementation. I find that it contains a few open issues as my patch indicates.

1. Position of debug output
2. Will [input parameter validation](https://en.wikipedia.org/wiki/Assert.h "Usage of assertions") be omitted when the preprocessor symbol "`NDEBUG`" would be defined? Would it make sense to use permanent checks there?
3. Do you care for [the usage of prefix (decrement) operators](http://en.cppreference.com/w/c/language/operator_incdec "Description for increment/decrement operators")?

**Comment by dcvmoole** [comment]
> Do you need another bug report to fix it?

No that is okay, thank you.

> [..]

It seems that at this point, you are indeed talking about issues entirely unrelated to the analysis tool. That means that at this point, we have gone entirely off the original topic of this issue, and that seems like a good point to stop the discussion. Therefore I am locking this issue.

> Will input parameter validation be omitted when the preprocessor symbol "NDEBUG" would be defined? Would it make sense to use permanent checks there?

The whole point of asserts is to check something that should already be guaranteed to be true (an _invariant_), so that at compile time one has the choice to either catch bugs early by detecting invariant violations, or eliminate the overhead of these theoretically redundant statements by disabling them. As such, asserts are *exactly* the right thing to use here.

> Do you care for the usage of prefix (decrement) operators?

That is a style issue, and the current code is fine.
