### ISSUE TITLE
sysenv: Invalid argument when building system

### ISSUE THREAD

**Issue by blakemcbride** [Stichting-MINIX-Research-Foundation/minix#15]
Greetings,

I downloaded the latest Minix from the current GIT on my Minix 3.3.0 system.  I built it with the command:

make build MKUPDATE=yes

The last few lines makes me question whether it was built correctly or not.  The last few lines are as follows:

...
install -N /usr/src/etc -c -p -r ../sbin/init/init /boot/minix/.temp/mod11_init
Done.
sysenv: Invalid argument
sysenv: Invalid argument
sysenv: Invalid argument
sysenv: Invalid argument
Build started at:  ...
Build finished at:  ...

I don't know if the "sysenv: Invalid argument" is significant.

Thank you.

**Comment by dcvmoole** [comment]
Hm well, I admit that that was not exactly an elegant change, but it was a one-time thing (commit f737eea6368426d3302d0075f13f73c4bc646e24). The sysenv failures might have some unexpected side effects, such as the new system not booting anymore (in the worst case). I think in the general case there is no problem though. If all else fails, installing a new development snapshot from http://download.minix3.org/iso/snapshot/ should work around it. After that, you can perform further upgrades without any issues. In any case, thank you for the report; I'm closing this issue merely because there's nothing we can do about it anymore.
