### ISSUE TITLE
A directory named aux has been added to the repository

### ISSUE THREAD

**Issue by antoineL** [Stichting-MINIX-Research-Foundation/minix#16]
Such a name is taboo on a regular Windows file system; as such, any attempt to check out the MINIX git tree on a Windows machine will end with
`    fatal: cannot create directory at 'external/mit/xorg/lib/xcb-util/aux': Invalid argument`

**Comment by dcvmoole** [comment]
I noticed the same, but, what can we do? That part of the source code is not ours; I can only assume NetBSD has the same problem (http://ftp.netbsd.org/pub/NetBSD/NetBSD-current/src/external/mit/xorg/lib/xcb-util/aux/)..

**Comment by dcvmoole** [comment]
Given that we ourselves basically cannot resolve this issue, is it okay if we close this issue? My general thought is that in order to keep the issue tracker manageable, we should close issues that won't ever see successful resolution, but I'm open to input here (to be clear, this is an administration consideration and does not change the fact that the issue you report is real and annoying).
