### ISSUE TITLE
X server unstable under stress

### ISSUE THREAD

**Issue by boricj** [Stichting-MINIX-Research-Foundation/minix#163]
I'm investigating pkgsrc compilation failures so I'm doing lots of compilations (both of MINIX source code and pkgsrc) inside xterm windows, but the reliability of the graphical environment is really bad under stress.

The xterm windows hosting the `make` commands get killed from time to time and now the X server itself crashed :

![snapshot1](https://cloud.githubusercontent.com/assets/9872969/17651933/33c51234-6271-11e6-9ffc-71d4b1e4917f.png)

I'm running MINIX-current a few commits behind (I'm at 3083d60) on a QEMU VM with 2 GiB of RAM and out-of-the-box X11+twm. The crashes seems to happen at random, but they are frequent enough that I haven't managed to complete the compilation of MINIX's sources under X11 by a long shot. Compilation under tty seems stable so far however.

**Comment by boricj** [comment]
Testing a bit further suggests that instability is especially prevalent when compiling both MINIX sources and pkgsrc packages at the same time, or basically just doing anything more than one graphical thing at a time (I just crashed TWM merely by opening a xterm while compiling MINIX inside a xterm).

It's still utterly random, but it seems to happen when the X server itself is under stress when multiple graphical programs are concurrently making lots of X11 stuff.

**Comment by dcvmoole** [comment]
As a step towards a bottom-up approach to debugging this, does addr2line happen to produce any useful output on that stacktrace? The 0xf100xxxx address means X is engaged in a system call, so a first possible thing to check is whether it's actually calling abort() itself there (i.e., kill(getpid(), SIGABRT), resulting in the signal 6) and if so, what piece of code within X is actually calling abort() and why..

**Comment by boricj** [comment]
Unfortunately, `addr2line` didn't produce any usable output. I'll build from scratch with `MKDEBUG=yes` and `MKDEBUGLIB=yes` and I'll try to reproduce this again.

**Comment by boricj** [comment]
I finally managed to make `MKDEBUG` and `MKDEBUGLIB` work (I'll make a pull request about that soon), so I have debugging symbols for everything now. I resumed stress-testing and so far I have a couple of `xterm` and `twm` crashes, including one with a stack trace (which just points to a signal handler) and its core dump.

GitHub doesn't allow uploading arbitrary binary files in this comment section, any preference where I should stash the core files and the debugging symbols online ? I have a Google account, I can put them inside a public Google Drive folder.

**Comment by dcvmoole** [comment]
Somehow I completely missed your last post here, sorry! The coredumps themselves are not too useful, since we have no utilities to analyze them (I believe? we should work on this.. anyhow). The addr2line text output from the stacktrace of the crash would be the most useful piece of information, if at all meaningful. A crash in a signal handler would be somewhat unexpected but not impossible, but there should (hopefully) then also be a part of the stacktrace that shows what the program was doing prior to getting a signal handler invoked.

**Comment by sambuc** [comment]
@boricj Since the rework of UDS, I have noticed two things:
 1. adding `127.0.1.1 minix minix.`  in `/etc/hosts`
     when using the default hostname of "minix" speeds up greatly the start of X11
 2. I have been able to build a full `make build` without issue from within X11, as well as use `/usr/pkgsrc/minix/pbulk-ng.sh`

Can you give it a try as well? I think we had some oddities in our UDS implementation and the problem was coming from there.

**Comment by boricj** [comment]
I'll give it a try when I'll have access to my main computer tomorrow.

**Comment by boricj** [comment]
I've been hammering X11 with concurrent compilations running under `xterm`, nothing to report.

Looks like X11 is stable now. Closing the issue.
