### ISSUE TITLE
A potential bug of handling interrupt in audio_fw.c

### ISSUE THREAD

**Issue by XidianGeneral** [Stichting-MINIX-Research-Foundation/minix#190]
Recently, I write a new sound card driver based on audio_fw.c, but I find a potential bug in this code.
There is a function handling sound card interrupt:
```
static void msg_hardware(unsigned int UNUSED(mask))
{
	int i;

	/* loop over all sub devices */
	for ( i = 0; i < drv.NrOfSubDevices; i++) {
		/* if interrupt from sub device and Dma transfer 
		   was actually busy, take care of business */
		if( drv_int(i) && sub_dev[i].DmaBusy ) {
			if (sub_dev[i].DmaMode == WRITE_DMA)
				handle_int_write(i);
			if (sub_dev[i].DmaMode == READ_DMA)
				handle_int_read(i);
		}
	}

	/* As IRQ_REENABLE is not on in sys_irqsetpolicy, we must
	 * re-enable out interrupt after every interrupt.
	 */
	if ((sys_irqenable(&irq_hook_id)) != OK) {
	  printf("%s: msg_hardware: Couldn't enable IRQ\n", drv.DriverName);
	}
}
```
The function drv_int() is used to read the interrupt status, and it is called for N times if there are N sub devices. It means that interrupt status is read for N times.
However, in some sound cards, the interrupt status is cleared when it is read, or the developer may clear the interrupt status in drv_int(). In this case, only sub_dev 0 can get interrupt status, and sub_dev 1...N can not get correct interrupt status.
A typical problem is that recording sub devices (sub_dev 1) can not correctly handle interrupt in the above case.

I want to know whether my opinion is right.

Thanks in advance,
Bai

**Comment by dcvmoole** [comment]
Hello! I think there are several ways to look at this issue. I think the best way forward is indeed to consider this a bug. Specifically, in commit 842c4eda, the call to drv_int_sum() got lost as part of removing the while-loop around the code you quoted. I think that call should be restored, but as part of an if-block rather than a while-block.

Then, what you can do in your implementation, is load the entire interrupt status in your implementation of drv_int_sub() and store it somewhere, e.g. in a global variable. Then, from your implementation of drv_int(), you can simply check against that global variable. The implied guarantee is that before calling drv_int() one or more times, libaudiodriver will always first call drv_int_sub() once.

Does that sound reasonable? If so, I'd be happy to add that if-block.

**Comment by XidianGeneral** [comment]
I think your idea is good.

**Comment by dcvmoole** [comment]
Cool! Fix pending.

**Comment by dcvmoole** [comment]
Fix merged, please let me know if there are any problems with it.

**Comment by XidianGeneral** [comment]
I have tested the fix in my sound card drivers and Minix es1371 driver, and it works well :)

**Comment by dcvmoole** [comment]
Glad to hear :)
