### ISSUE TITLE
pre-steps of make build in docs/UPDATING

### ISSUE THREAD

**Issue by deulgaonkaranup** [Stichting-MINIX-Research-Foundation/minix#208]
When i try to execute the steps in docs/UPDATING 

for t in gencat locale mkcsmapper mkesdb mklocale
do
   make -C /usr/src/usr.bin/$t all install
done

it gives me error:

![image](https://cloud.githubusercontent.com/assets/16316059/22175748/0cf962ae-dfc1-11e6-83a0-e5b62a8f5ce5.png)

**Comment by dcvmoole** [comment]
Hello! Due to the rapid development of MINIX3, we are not able to guarantee that it is possible to upgrade from any old revision to the latest revision in a single step. In particular, it seems that you want to upgrade from the 3.3.0 release (or any other revision from before Nov 2015) to minix-current, and this is unfortunately not something that is supported. We strongly recommend that you install the latest snapshot (which currently is 3.4.0-RC4) from http://download.minix3.org/iso/snapshot/ first instead. After that, you will be able to upgrade to minix-current in a single step.

I hope you don't mind that I close this issue, as this isn't a bug in MINIX3, but rather a limitation resulting from our current development process.
