### ISSUE TITLE
mined: built without UNIX defined.

### ISSUE THREAD

**Issue by tcort** [Stichting-MINIX-Research-Foundation/minix#43]
`mined` has ifdefs to do a lot of conditional compilation based on `UNIX` being defined or not. For example, if `UNIX` is defined it does the termcap song and dance to learn about the terminal (e.g. `tgetent`, `tgetstr`, `tgetnum`, etc) and uses other terminal i/o routines (e.g. `tputs`). If `UNIX` isn't defined, it just uses simple functions like `write`.

At present `UNIX` is not defined during compilation. In fact, it won't even compile with `UNIX` defined because `mined.h` undefs `NULL` and does other things crazy things like redefining `putchar()`.

My feeling is that `mined` should be updated to compile with `UNIX` defined and use the proper terminal routines. I also think that once that's working, the `!UNIX` sections of code should be removed. What are some thoughts on this? I'm happy to do the work, but I wanted to get others opinions before I sink too much time into this.

**Comment by antoineL** [comment]
On 22/03/2015 21:02Z, Thomas Cort wrote:
> What are some thoughts on this?

I am (or was) a big fan and user of mined, and I saw two big problems
with it:
- combination Ctrl-@ (which is used to "mark" and thus is basic to
perform any copy or cut operations) is filtered by the keyboard layer in
Minix 3; I proposed to have Ins as well, but it was not accepted.
- manual (with the key mapping) was in the man1x category, sourcing
mnx.mac, which get MIA during the transition to the NetBSD userland.

Before that, Will Rose also proposed enhancements to mined, and they
were also not accepted within mainstream MINIX 2.

I am under the impression that mined is due to be kept as is, much like
a relic. Perhaps it is/was used as support for homework assignments in
VU courses, which would explain the resistance to enhance it. Otherwise,
perhaps the plan is to stick to "real" UNIX editors as nvi or vim (or
elvis when involving MINIX 2), with emacs as an option to the
"supporters of the opposite camp", but without wasting the scarce
support resources on other options like mined or elle.


Antoine

**Comment by tcort** [comment]
> I proposed to have Ins as well, but it was not accepted.

Is this the patch? It looks like it was accepted.... "Mined: allow Ins to mark" -- commit fc1c7a348338bde57bbc190909aae495aa948bfb

**Comment by dcvmoole** [comment]
Well, I don't know about the MINIX2 days but there is certainly no plan to preserve mined as it is now. The "problem" may be more that among the current group of people with commit access, mined is not exactly heavily used, and it's always a bit risky to commit something if you have no idea whether a patch is in fact an improvement. By all means go ahead with whatever you guys decide is best though. I'd be happy to submit any older patches to gerrit if anything is still pending?

**Comment by antoineL** [comment]
> Is this the patch? It looks like it was accepted

Yup. I did not even notice it was accepted :^)
Thanks Tom to have unburied this.


Antoine

**Comment by sambuc** [comment]
There as been interest around that editor lately, so I think we might as well just move it to `minix/usr.bin`, as part of this change set.

I think this would be a good thing to get it to compile using the proper termcap functions, and remove the UNIX `#ifdef`. Hopefully MINIX is now up to the task. This would simplify the code, and improve it's portability.
