### ISSUE TITLE
x86_hdimage.sh pollutes the source directory's parent with object files

### ISSUE THREAD

**Issue by ghost** [Stichting-MINIX-Research-Foundation/minix#64]
Upon finishing the crosscompiling steps (http://wiki.minix3.org/doku.php?id=developersguide:crosscompiling), you can see that MINIX's object files are placed in ~/src/third-party/obj.i386 (for example), rather than ~/src/third-party/minix/obj.i386.

It comes down to this line in releasetools/x86_hdimage.sh:

> : ${OBJ=../obj.${ARCH}}

No problem, right?  Just cd into the releasetools/ directory and run ./x86_hdimage.sh from there: ../obj.i386 is obviously supposed to be relative the releasetools/ directory.  Wrong.

x86_hdimage.sh will actually refuse to run from the releasetools/ directory, and in fact, refuse to run from any directory other than the source root:

>   echo "Please invoke me from the root source dir, where ${BUILDSH} is."

**Comment by Tookmund** [comment]
The idea is to leave them out of the git repo AIUI
if the problem is 
: ${OBJ=../obj.${ARCH}}
What about using 
: ${OBJ=../minix.obj.${ARCH}}
Instead?

**Comment by colbyrussell** [comment]
On 04/15/2015 06:19 PM, Jacob Adams wrote:
>
> The idea is to leave them out of the git repo AIUI
>

What's the benefit of that?  The source directory already has an 
extensive .gitignore.  Probably too extensive.  There's stuff in there 
that probably shouldn't be, while obj.i386, obj.evbearm-el, et cetera 
*should* be.

-- 
Colby Russell

**Comment by Tookmund** [comment]
See #32

**Comment by sambuc** [comment]
You can specify where to put your object directory in multiple ways. The default is NOT to put it in the sources to prevent pollution of the source tree.

You can:
 a. export OBJ from your shell:
     # export OBJ=<my preferred location>
     # ./releasetools/x86_hdimage.sh
 b. Set it on the command line directly (I prefer this way personally):
    # OBJ=<my preferred location> ./releasetools/x86_hdimage.sh

Btw, this also applies to the *other* variables of the scripts.

> On 16 avr. 2015, at 01:23, Colby Russell <notifications@github.com> wrote:
> 
> On 04/15/2015 06:19 PM, Jacob Adams wrote:
> >
> > The idea is to leave them out of the git repo AIUI
> >
> 
> What's the benefit of that? The source directory already has an 
> extensive .gitignore. Probably too extensive. There's stuff in there 
> that probably shouldn't be, while obj.i386, obj.evbearm-el, et cetera 
> *should* be.

That is your personal opinion; there are also good reasons not to pollute the sources of a project with object files in the first place.

Ideally, when all dependencies on GPL software are removed, we will be able to have a read-only source tree, which is very convenient to have multiple builds with different targets / build option from the same source directory.

Had it been the case, I would be able to run the build as a specific user without write rights to the source tree and I wouldn't recently have lost my whole source tree & .git (so no going back) due to a bug in a patch I tested.

Such things *are* a matter of personal situation, goals and taste. We have left them as configurable options for that very reason. We provide what we think are reasonable defaults, but you are welcome to adapt those in your environment if they don't suit your use case.

**Comment by colbyrussell** [comment]
Thanks for taking the time to respond, but you've responded as if you 
would to a ticket for end-user support, i.e., giving me steps to work 
around this for my own use.  Again, I appreciate your willingness to do 
that.

But end-user support isn't really the purpose of a bugtracker, and it's 
not why I filed this bug.  I have in place custom workflow scripts, and 
they already handle this adequately.  The motivation for filing the bug 
is that:

a) projects that move out of their own space and start messing with 
things in others' spaces are considered not well-behaved, especially 
when doing so unannounced
b) MINIX does (a) by default
c) I would have thought (a) to be a fairly non-controversial statement 
and for (b) to be have been mostly an artifact of happenstance, and to 
have been received with not much more difficulty than the effort it took 
to point it out

... but I didn't expect to end up in a discussion about the merits of 
alternative philosophies to (a).  I don't really intend to, either.  
Like I said, I was fully expecting a response more along the lines of 
"ah, yeah..." and possibly a "we know" or "we just haven't gotten around 
to doing anything about it yet" followed up by the token "patches 
welcome".  Having now found myself in a completely different situation, 
my response now is to shrug and say, "well okay then", rather than to 
spend any serious effort trying to make a case for why (a) is a good 
thing to avoid.

On 04/16/2015 01:39 AM, Lionel Sambuc wrote:
> we will be able to have a read-only source tree, which is very 
> convenient to have multiple builds with different targets / build 
> option from the same source directory.

Good goals.  (Building MINIX on MINIX without having to be root for the 
build step--deferring that requirement until the part where the newly 
built kernel/modules get swapped in--would also be among them as good 
goals.) But there are multiple ways to handle this that avoid (a), and 
in any case, it seems to be an instance of favoring a specific set of 
uncommon preferences over sane defaults. Cf:

> I wouldn't recently have lost my whole source tree & .git (so no going 
> back) due to a bug in a patch I tested.

*shrugs*

Okay then.

-- 
Colby Russell

**Comment by boricj** [comment]
@sambuc I believe I'm the author of said patch.

I'm so, so sorry about that. I found it the hard way a bit too late... Twice.

Never underestimate the power of "rm -rf" inside a shell script. That thing's DANGEROUS.

**Comment by dcvmoole** [comment]
With all due respect to everyone involved: seeing as this discussion has not resulted in agreement on a concrete problem to be resolved, I believe there is no reason to keep the issue open.
