### ISSUE TITLE
Pipe performance problems

### ISSUE THREAD

**Issue by boricj** [Stichting-MINIX-Research-Foundation/minix#65]
Pull request #63 shows that the pipe implementation in Minix has performance problems. During installation with a ISO generated by this branch, extracting the tarball sets with pax is tremendously slow, and "top" suggests that the CPU is mostly idle during the operation.

**Comment by dcvmoole** [comment]
I would be interested in a minimal way to reproduce this problem..

**Comment by boricj** [comment]
I haven't touched this part in a while, but I believe the relevant part of the setup script was

```
# Running from the installation CD.
for set in /i386/binary/sets/*.tgz; do
    echo "Extracting $(basename "$set")..."
    COUNT_FILES=$(cat $(echo "$set" | sed -e "s/\.tgz/\.count/"))
    (cd /mnt; pax -rz -f $set -v -pe 2>&1 | progressbar "$COUNT_FILES" || exit)
done;
```
Here's the tests I ran just now (QEMU, /mnt is a mfs partition, /mnt/minix-base.tgz is straight from new_iso_goodness3 and has 1508 files) :
* running `time gunzip < /mnt/minix-base.tgz > /usr/minix-base.tar` takes 11.65 secs, top says CPU 2% idle,
* running `time tar -xvf /usr/minix-base.tar` takes 7.76 secs, top says CPU 3% idle,
* running `time pax -rz -v -pe -f /mnt/minix-base.tgz` takes 1:55.15 secs, top says CPU is ~70% idle, the equivalent `tar` command takes as much time.

I'll post benchmarks with the installation CD as soon as it is compiled, but in the meantime I distinctly remember setup's extraction part being ridiculously slow (taking at least more than 7 minutes to extract minix-base.tgz) with top saying CPU is >90% idle.

**Comment by boricj** [comment]
From the installation CD, using my branch new_iso_goodness3 :
* `time tar -xzvf /i386/binary/sets/minix-base.tgz` takes 1:40.75 secs, CPU usage is ~75% idle and ~15% kernel according to `top`,
* `time pax -rz -v -pe -f /i386/binary/sets/minix-base.tgz 2>&1 | progressbar 1508` takes 1:47.90 secs, CPU usage is ~70% idle according to `top`,
* the extraction of minix-base.tgz from the setup script took 1:43 secs.

Strangely it's nowhere near as slow as I remember (perhaps I filed that issue before I rewrote isofs again? I remember the old isofs, which is still in Minix's master branch, taking *5 minutes* just to reach the login prompt), but the fact remains that invoking gunzip and tar in a pipe is much slower than running them separately for no obvious reason.

**Comment by dcvmoole** [comment]
Got it, thank you! Indeed, I managed to reproduce the same problems, using a tar.gz made from /usr/src/minix/drivers (including objects, in particular the ramdisk) which comes up to about 20MB. Running gunzip and then tar separately takes about 0.2 and 2 seconds respectively, whereas all of "gunzip -c drivers.tar.gz | tar xf -", "tar zxf drivers.tar.gz", "pax -rzf drivers.tar.gz" and even "cat drivers.tar | tar xf -" take in the range of 39 to 55 seconds. The last case confirms that this is really a issue with pipes.

My first guess would be that the hard limit of PIPE_BUF is causing unnecessary blocking on the pipe. As I happened to notice the other day, Linux and NetBSD both use an actual pipe size which is much larger than PIPE_BUF, even though MINIX3 already uses a PIPE_BUF value that is larger than both of theirs. It should be possible to let our PFS use a somewhat more flexible pool of memory, although low-memory and out-of-memory conditions are to be considered in that case. Moreover, VFS will have to be changed accordingly. This is not easy to do even for testing. Just globally increasing PIPE_BUF could make for a good first test, but not an actual solution.

However, IF this is indeed what's going on here, then the CPU usage stats are also off, since the system is never actually idle. This would then be a separate issue.

It's also possible that I'm overlooking a completely different issue. I'm now thinking about adding timestamping support to trace(1)..

To be continued.

**Comment by dcvmoole** [comment]
Alright, I found the problem, and it is something completely different. It's actually my fault: VFS used to have an exceptional yield() call which ensured that threads used to resume suspended pipe activity would actually run straight away. At some point I made a wrong assumption about the reason behind its existence and removed it, with as result that VFS wouldn't even look at a pipe resumption thread until it got a new message, thus explaining the slowdown as well as the idle CPU. Fortunately the issue is trivial to fix, and the fix actually improves the internal control flow in VFS somewhat, too. Patch submitted to gerrit/jenkins.
