### ISSUE TITLE
Compiling a source tree under vbfs with clang

### ISSUE THREAD

**Issue by hexcoder-** [Stichting-MINIX-Research-Foundation/minix#96]
Hi,

I am using Minix 3.3.0 on VirtualBox on Ubuntu 14.04 on amd64.

I observed the following error when using shared folders with the vbfs file system.
After mounting I tried to compile some C source files located under the shared folder with clang.

The clang compiler complained with this weird error for almost every source file:
fatal error: file 'make.c' modified since it was first processed
1 error generated.

(Of course there was no other process running, which could interfere with the source files. Not on the host, not on the guest).

The problem vanished when I compiled with a copy of the source tree from the native file system.

BTW: This error message vanished also under vbfs when the source file was shortened enough.
Of course then the compiler complained about the errors I had introduced by shortening, but that was expected...

So, i conclude there might be a bug in the implementation of the vbfs file system.

To reproduce try to compile a not too short C source file from a vbfs mounted directory with clang.
My example file had an original size of 53,1 kilobytes.

Regards, Heiko

**Comment by dcvmoole** [comment]
Hello! I just did a very quick test on MINIX3-current, compiling a 43KB file with clang on vbfs, and this worked fine. We did fix some issues since the 3.3.0 release that might explain the difference. Could you please upgrade to current, and see if you can still produce the error? Upgrading instructions are here: wiki.minix3.org/doku.php?id=developersguide:trackingcurrent - it might help to first start with the latest developer snapshot from http://download.minix3.org/iso/snapshot/ (the latest is still quite old and may itself not yet have a fix for this issue, but I'm not sure). Thank you!

**Comment by hexcoder-** [comment]
The issue is gone with minix3-current as of today. This issue can be closed. Thanks for fixing.

**Comment by dcvmoole** [comment]
That's great to hear! Thank you very much for testing!
